# Generated by Django 2.1.4 on 2019-03-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20190311_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='grade',
            new_name='academic_year',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='last_name',
            new_name='work_unit',
        ),
        migrations.RemoveField(
            model_name='document',
            name='stt',
        ),
        migrations.AddField(
            model_name='document',
            name='id_student',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
