# Generated by Django 2.1.4 on 2019-03-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20190317_0355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Student',
        ),
    ]
