# Generated by Django 2.1.4 on 2019-03-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20190317_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
