# Generated by Django 2.1.4 on 2019-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_auto_20190401_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='topic_type',
            field=models.CharField(choices=[('kltn', 'khoa luan tot nghiep'), ('nckh', 'nghien cuu khoa hoc')], max_length=4, null=True),
        ),
    ]
