# Generated by Django 2.1.8 on 2019-04-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0014_auto_20190403_2252'),
        ('list', '0014_auto_20190403_2100'),
    ]

    operations = [
    ]
