# Generated by Django 2.1.4 on 2019-03-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20190320_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pdf',
            field=models.FileField(upload_to='media'),
        ),
    ]
