# Generated by Django 2.1.4 on 2019-03-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_auto_20190320_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='pdf',
            new_name='file',
        ),
    ]
