# Generated by Django 2.1.4 on 2019-04-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_auto_20190326_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kltn',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nckh',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
