# Generated by Django 2.1.4 on 2019-04-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0016_auto_20190416_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
