# Generated by Django 2.1.7 on 2019-05-03 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0017_auto_20190416_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
