# Generated by Django 2.1.7 on 2019-05-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0018_auto_20190503_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
