# Generated by Django 2.1.7 on 2019-05-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0022_auto_20190505_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
