# Generated by Django 2.1.7 on 2019-05-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0023_student_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
    ]
