# Generated by Django 2.1.7 on 2019-05-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0024_remove_student_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
