# Generated by Django 2.1.7 on 2019-05-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0025_auto_20190505_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
    ]
