# Generated by Django 2.1.7 on 2019-05-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0031_auto_20190506_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birth_date',
            new_name='birth',
        ),
    ]
